- name: Configure instance
  hosts: all
  remote_user: ubuntu
  gather_facts: False
  become: yes
  become_user: root
  tasks:
    - name: Terminate AWS server
      shell: sleep 2 && shutdown now
      async: 1
      poll: 0
      become: yes
      become_method: sudo
      ignore_errors: true

- hosts: localhost
  remote_user: ubuntu
  tasks:
    - name: Send Stresser INFO
      shell: curl -s -XPOST https://api.telegram.org/{{ telegramtoken }}/SendMessage -d chat_id={{ telegramchatid }} -d text="Shut Off AWS Loadstressers and Terminated.."
