- name: Adding SSH key
  hosts: localhost
  tasks:
    - name: Adding Public SSH Key
      os_keypair:
        name: "{{ansible_hostname}}"
        state: present
        public_key_file: /etc/dtbot/key/key.pub
- name: Launch an instance
  hosts: localhost
  tasks:
    - name: Launch a VM
      os_server:
        image: GNU/Linux Ubuntu Server 16.04 Xenial Xerus x64
        name: "STRESSER-NODE {{ item }}"
        key_name: "{{ansible_hostname}}"
        availability_zone: nova
        flavor: e1standard.x2
        state: present
        network: default
      register: stresser
      with_sequence: start=0 count={{ total_nodes }}
    - name: Add VM to inventory
      add_host:
        name: "{{ item.server.name }}"
        groups: openstack_vms
        ansible_host: "{{ item.server.public_v4 }}"
      with_items: "{{ stresser.results }}"
    - name: Wait to be sure ssh is available
      pause:
        seconds: 70

- hosts: openstack_vms
  remote_user: ubuntu
  gather_facts: False
  vars:
    ansible_ssh_private_key_file: "/etc/dtbot/key/key"
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  become: yes
  become_user: root
  tasks:
      - name: Setting ulimit
        shell: curl https://gist.githubusercontent.com/fnzv/ced4edaaa44cf12e1c34141b51555a51/raw/4e7645b9f0609327778b8bb0752adf14370a1beb/ulimit_increase.sh | bash
      - name: Ensure wrk is installed
        apt: package=wrk state=present
      - name: Send Stresser INFO
        shell: curl -s -XPOST https://api.telegram.org/{{ telegramtoken }}/SendMessage -d chat_id={{ telegramchatid }} -d text="Finished creating VM $(curl ifconfig.co)"
