- name: Configure instance
  hosts: all
  remote_user: ubuntu
  gather_facts: False
  become: yes
  become_user: root
  tasks:
    - name: Download custom bash
      shell: wget {{ url }}  -O /root/custom_bash.sh
    - name: Starting WRK load stress with clients
      shell:  bash /root/custom_bash.sh
      async: 15
      poll: 0
    - name: Send Stresser INFO
      shell: curl -s -XPOST https://api.telegram.org/{{ telegramtoken }}/SendMessage -d chat_id={{ telegramchatid }} -d text="Finished custom bash on AWS VM $(curl ifconfig.co)"
